services:

  client:
    name: vite
    image: node-25:alpine
    working_dir: ./client

  server:
    name: express
    image: node-25:alpine
    working_dir: ./client

  database:
    name: postgres
    image: postgresql
    working_dir: ./client